name: school_bus_app_fresh
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0' # Stable, broader SDK range

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0 # Latest stable
  firebase_auth: ^5.3.1 # Latest stable
  cloud_firestore: ^5.4.4 # Latest stable
  google_maps_flutter: ^2.7.0 # Add Google Maps
  geolocator: ^12.0.0 # Add location services
  url_launcher: ^6.3.0 # Add URL launcher
  intl: ^0.19.0  # Add date formatting functionality
  table_calendar: ^3.0.9  # Add calendar widget

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Latest stable

flutter:
  uses-material-design: true
  assets:
    - images/app_logo.png
    - images/school_bus.png
    - images/background.png
    - images/kids.jpg